// Generated by hand — this plugin's browser half.
//
// 客户端 bundle 的格式（与官方 tsdown 预设产物一致）：
//     window.__ModuleLoader__.load({ id, factory: function (require) { ... return plugin }})
// 工厂收到的 require 用来解析 dsh.client.inject 里声明的模块。本插件不依赖任何
// 平台模块（只碰 DOM 和 fetch），所以不需要打包工具，直接手写即可。
//
// 为什么要有这一半：宿主侧的 webserver/index-inject 只在「宿主渲染 index.html」时生效，
// web 端可以，桌面端窗口加载的是打包页面（dsh-app://app/），那条路吃不到。
// 客户端插件跑在渲染进程里，web 与桌面端完全一致 —— 样式和壁纸在这里自己挂。
//
// 它与宿主半边的关系：宿主算好完整 CSS（--dsw-* token + 载体 CSS）并通过
// GET /dsh-visual/state 给出来，这里只负责"把结果贴到页面上"。
window.__ModuleLoader__.load({
  id: 'dsh-visual-system',
  factory: function () {
    'use strict';

    const ROUTE = '/dsh-visual';
    const STYLE_ID = 'dsh-visual-system-style';
    const MEDIA_ID = 'dsh-visual-media';
    const POLL_MS = 4000;

    /** 当前生效的素材地址，避免重复重建 DOM。 */
    let appliedSrc = null;

    function ensureStyle() {
      let style = document.getElementById(STYLE_ID);
      if (!style) {
        style = document.createElement('style');
        style.id = STYLE_ID;
        document.head.appendChild(style);
      }
      return style;
    }

    function removeMedia() {
      document.getElementById(MEDIA_ID)?.remove();
      appliedSrc = null;
    }

    function renderMedia(media) {
      if (!media) {
        removeMedia();
        return;
      }
      let carrier = document.getElementById(MEDIA_ID);
      if (!carrier) {
        carrier = document.createElement('div');
        carrier.id = MEDIA_ID;
        carrier.setAttribute('aria-hidden', 'true');
        // body 的第一个子元素：图层顺序见 README（载体要压在应用表面之下）
        document.body.insertBefore(carrier, document.body.firstChild);
      }
      if (appliedSrc === media.url && carrier.firstElementChild) return;

      const tag = media.kind === 'video' ? 'video' : 'img';
      const element = document.createElement(tag);
      element.src = media.url;
      if (tag === 'video') {
        element.autoplay = true;
        element.muted = true;
        element.loop = true;
        element.playsInline = true;
        element.setAttribute('disablepictureinpicture', '');
      } else {
        element.alt = '';
        element.decoding = 'async';
      }
      if (media.focus) element.style.objectPosition = media.focus;

      carrier.replaceChildren(element);
      appliedSrc = media.url;
    }

    function applyState(state) {
      if (!state || typeof state.css !== 'string') return;
      const style = ensureStyle();
      if (style.textContent !== state.css) style.textContent = state.css;
      renderMedia(state.media);
    }

    async function refresh() {
      const response = await fetch(`${ROUTE}/state`, { headers: { accept: 'application/json' } });
      if (!response.ok) throw new Error(`state ${response.status}`);
      applyState(await response.json());
    }

    /**
     * 客户端插件体。
     * @param ctx - 浏览器侧 cordis 上下文。
     */
    function apply(ctx) {
      let timer = null;
      const tick = () => {
        // 视觉失败绝不能影响页面：出错只记一条警告，下一次轮询继续。
        refresh().catch((error) => console.warn('[dsh-visual-system]', error?.message ?? error));
      };
      tick();
      timer = setInterval(tick, POLL_MS);

      ctx.effect(() => () => {
        if (timer !== null) clearInterval(timer);
        document.getElementById(STYLE_ID)?.remove();
        removeMedia();
      }, 'dsh-visual-system: theme');
    }

    return { name: 'dsh-visual-system', apply };
  },
});
